include = ["*.py", "*.ipynb"] # 检查所有 Python 文件和 Jupyter Notebook 文件

extend-exclude = [ # 排除以下路径和文件
    ".git",        # Git 仓库目录
    "__pycache__", # Python 缓存目录
    "build",       # 构建目录
]

line-length = 200 # 每行最大字符数
indent-width = 4  # 缩进使用 4 个空格

[lint]
select = [ # 启用的规则类别
    "E",   # PEP8 基础错误（如缩进、空格）
    "F",   # Pyflakes 静态检查（如未使用变量）
    "N",   # PEP8 命名规范（如变量名格式）
    "W",   # PEP8 警告（如代码风格建议）
    "D",   # pydocstyle 文档字符串规范
    "NPY", # NumPy 特定规则
    "RUF", # Ruff 特有规则
]

ignore = [ # 忽略的具体规则
    "D105",   # 允许魔术方法（如 __init__）不写文档
    "D107",   # 不单独为 __init__ 写文档（合并到类文档）
    "D301",   # 允许文档字符串中使用反斜杠
    "D205",
    "D415",   # 允许省略文档字符串的总结行
    "N816",
    "N806",
    "N803",   # 允许大写变量名（如常量或特殊用途）
    "D214",   # 忽略 Trigger 模块的缩进问题（适配 Google 风格）
    "RUF002", # 允许在注释中使用中文逗号
    "RUF003", # 允许在注释中使用中文逗号
]


[lint.pydocstyle]
convention = "google" # 强制使用 Google 风格的文档字符串格式


[lint.per-file-ignores]
# 测试文件无需完整文档
"**/pytest/*" = ["D", "F811", "N999"] # 忽略文档、未定义名称、占位符检查
# 文档示例文件无需严格格式
"sphinx-doc/howto/*.py" = ["D"]


[format]
indent-style = "space"          # 缩进用空格（非 Tab）
line-ending = "auto"            # 自动检测换行符（LF/CRLF）
docstring-code-line-length = 72 # 文档字符串中的代码行长度限制
docstring-code-format = true    # 启用文档字符串内的代码格式化
